export const REDIS_COMMAND = Symbol('REDIS_COMMAND');
export const REDIS_SOCKET_PUBLISHER = Symbol('REDIS_SOCKET_PUBLISHER');
export const REDIS_SOCKET_SUBSCRIBER = Symbol('REDIS_SOCKET_SUBSCRIBER');
export const REDIS_ROUTING_SUBSCRIBER = Symbol('REDIS_ROUTING_SUBSCRIBER');

export const REDIS_INSTANCE_HEARTBEAT_MS = 10_000;
export const REDIS_INSTANCE_STALE_MS = 30_000;
export const REDIS_QUEUE_LEASE_MS = 45_000;
export const REDIS_PRIVATE_ROOM_TTL_SECONDS = 15 * 60;
export const REDIS_ROOM_TTL_SECONDS = 15 * 60;
export const REDIS_COMMAND_TTL_SECONDS = 15 * 60;
