import { QuestionItem, ReviewCase, SkillCoverage, AuditLogEntry } from '@/types/admin';

export const MOCK_QUESTIONS: QuestionItem[] = [
  {
    id: 'q-tiu-analogi-01',
    sourceKey: 'TIU-ANA-2024-001',
    revision: 2,
    target: 'cpns',
    category: 'TIU',
    subcategory: 'Verbal',
    primarySkillId: 'analogi_kata',
    prerequisiteSkillIds: ['kosakata_dasar'],
    prompt: 'KOSONG : HAMPA = KELAS : ... ?',
    options: ['Sekolah', 'Ruang Belajar', 'Tingkatan', 'Siswa', 'Pelajaran'],
    correctOptionIndex: 2,
    explanation: 'Kosong dan hampa merupakan sinonim. Hubungan yang sama berlaku untuk Kelas dan Tingkatan (sinonim dalam arti strata/kategori).',
    difficulty: 3,
    standardTimeLimitMs: 45000,
    expectedTimeMs: 28000,
    curriculumWeight: 1.0,
    assessmentEligible: true,
    qualityState: 'approved',
    smeApproved: true,
    approvedAt: '2025-08-10T09:00:00Z',
    approverReference: 'SME-DOC-TIU-04',
    active: true,
    lastUsedAt: '2026-08-31T14:20:00Z',
    metrics: {
      totalAttempts: 1420,
      unseenAttempts: 890,
      overallAccuracy: 68.4,
      unseenAccuracy: 62.1,
      seenUnseenGap: 6.3,
      medianResponseTimeMs: 24500,
      timeoutRate: 3.2,
      hintRate: 7.8,
      discriminationIndex: 0.44,
      distractors: [
        { optionIndex: 0, text: 'Sekolah', count: 180, percentage: 12.7, isCorrect: false },
        { optionIndex: 1, text: 'Ruang Belajar', count: 195, percentage: 13.7, isCorrect: false },
        { optionIndex: 2, text: 'Tingkatan', count: 971, percentage: 68.4, isCorrect: true },
        { optionIndex: 3, text: 'Siswa', count: 54, percentage: 3.8, isCorrect: false },
        { optionIndex: 4, text: 'Pelajaran', count: 20, percentage: 1.4, isCorrect: false }
      ],
      signals: []
    }
  },
  {
    id: 'q-tiu-silogisme-02',
    sourceKey: 'TIU-SIL-2024-042',
    revision: 1,
    target: 'cpns',
    category: 'TIU',
    subcategory: 'Logika',
    primarySkillId: 'silogisme_kategoris',
    prerequisiteSkillIds: ['premis_dasar'],
    prompt: 'Semua ilmuwan berpikir kritis. Sebagian ilmuwan gemar menulis artikel ilmiah. Kesimpulan yang benar adalah...',
    options: [
      'Semua yang gemar menulis artikel ilmiah berpikir kritis',
      'Sebagian yang berpikir kritis gemar menulis artikel ilmiah',
      'Semua yang berpikir kritis adalah ilmuwan',
      'Ilmuwan yang tidak berpikir kritis tidak gemar menulis artikel',
      'Tidak ada ilmuwan yang tidak gemar menulis'
    ],
    correctOptionIndex: 1,
    explanation: 'Premis 1: Semua A adalah B. Premis 2: Sebagian A adalah C. Kesimpulan: Sebagian B adalah C (Sebagian yang berpikir kritis gemar menulis artikel ilmiah).',
    difficulty: 4,
    standardTimeLimitMs: 60000,
    expectedTimeMs: 38000,
    curriculumWeight: 1.2,
    assessmentEligible: true,
    qualityState: 'under_review',
    smeApproved: false,
    approvedAt: null,
    approverReference: null,
    active: true,
    lastUsedAt: '2026-08-31T18:45:00Z',
    metrics: {
      totalAttempts: 980,
      unseenAttempts: 640,
      overallAccuracy: 24.5,
      unseenAccuracy: 18.2,
      seenUnseenGap: 6.3,
      medianResponseTimeMs: 54200,
      timeoutRate: 18.6,
      hintRate: 26.4,
      discriminationIndex: 0.12,
      distractors: [
        { optionIndex: 0, text: 'Semua yang gemar menulis artikel ilmiah berpikir kritis', count: 480, percentage: 49.0, isCorrect: false },
        { optionIndex: 1, text: 'Sebagian yang berpikir kritis gemar menulis artikel ilmiah', count: 240, percentage: 24.5, isCorrect: true },
        { optionIndex: 2, text: 'Semua yang berpikir kritis adalah ilmuwan', count: 120, percentage: 12.2, isCorrect: false },
        { optionIndex: 3, text: 'Ilmuwan yang tidak berpikir kritis tidak gemar menulis artikel', count: 110, percentage: 11.2, isCorrect: false },
        { optionIndex: 4, text: 'Tidak ada ilmuwan yang tidak gemar menulis', count: 30, percentage: 3.1, isCorrect: false }
      ],
      signals: ['low_accuracy', 'suspicious_distractor_0', 'high_timeout_rate']
    }
  },
  {
    id: 'q-twk-pancasila-03',
    sourceKey: 'TWK-PAN-2024-118',
    revision: 3,
    target: 'cpns',
    category: 'TWK',
    subcategory: 'Pancasila',
    primarySkillId: 'pancasila_sila_2',
    prerequisiteSkillIds: ['butir_pancasila'],
    prompt: 'Mengakui persamaan derajat, persamaan hak, dan kewajiban asasi setiap manusia tanpa membeda-bedakan suku, keturunan, agama, kepercayaan, jenis kelamin, kedudukan sosial, warna kulit dan sebagainya merupakan pengamalan sila ke...',
    options: ['Sila Pertama', 'Sila Kedua', 'Sila Ketiga', 'Sila Keempat', 'Sila Kelima'],
    correctOptionIndex: 1,
    explanation: 'Butir pengamalan sila ke-2 (Kemanusiaan yang Adil dan Beradab) salah satunya adalah mengakui persamaan derajat, hak, dan kewajiban asasi.',
    difficulty: 2,
    standardTimeLimitMs: 40000,
    expectedTimeMs: 18000,
    curriculumWeight: 1.0,
    assessmentEligible: true,
    qualityState: 'approved',
    smeApproved: true,
    approvedAt: '2025-09-01T10:00:00Z',
    approverReference: 'SME-DOC-TWK-11',
    active: true,
    lastUsedAt: '2026-08-31T20:10:00Z',
    metrics: {
      totalAttempts: 2150,
      unseenAttempts: 1350,
      overallAccuracy: 88.2,
      unseenAccuracy: 84.6,
      seenUnseenGap: 3.6,
      medianResponseTimeMs: 16200,
      timeoutRate: 1.1,
      hintRate: 2.3,
      discriminationIndex: 0.38,
      distractors: [
        { optionIndex: 0, text: 'Sila Pertama', count: 45, percentage: 2.1, isCorrect: false },
        { optionIndex: 1, text: 'Sila Kedua', count: 1896, percentage: 88.2, isCorrect: true },
        { optionIndex: 2, text: 'Sila Ketiga', count: 68, percentage: 3.2, isCorrect: false },
        { optionIndex: 3, text: 'Sila Keempat', count: 32, percentage: 1.5, isCorrect: false },
        { optionIndex: 4, text: 'Sila Kelima', count: 109, percentage: 5.0, isCorrect: false }
      ],
      signals: []
    }
  },
  {
    id: 'q-bumn-akhlak-04',
    sourceKey: 'BUMN-AKH-2024-009',
    revision: 1,
    target: 'bumn',
    category: 'Core Values',
    subcategory: 'AKHLAK',
    primarySkillId: 'akhlak_harmonis',
    prerequisiteSkillIds: ['nilai_utama_bumn'],
    prompt: 'Seorang karyawan selalu menghargai setiap orang apapun latar belakangnya, suka menolong orang lain, dan membangun lingkungan kerja yang kondusif. Perilaku ini mencerminkan core value BUMN...',
    options: ['Amanah', 'Kompeten', 'Harmonis', 'Loyal', 'Adaptif', 'Kolaboratif'],
    correctOptionIndex: 2,
    explanation: 'Panduan perilaku Harmonis: Menghargai setiap orang apapun latar belakangnya, suka menolong orang lain, membangun lingkungan kerja yang kondusif.',
    difficulty: 2,
    standardTimeLimitMs: 45000,
    expectedTimeMs: 22000,
    curriculumWeight: 1.0,
    assessmentEligible: true,
    qualityState: 'approved',
    smeApproved: true,
    approvedAt: '2025-07-20T12:00:00Z',
    approverReference: 'SME-DOC-BUMN-02',
    active: true,
    lastUsedAt: '2026-08-31T21:00:00Z',
    metrics: {
      totalAttempts: 1680,
      unseenAttempts: 1100,
      overallAccuracy: 91.5,
      unseenAccuracy: 89.0,
      seenUnseenGap: 2.5,
      medianResponseTimeMs: 19400,
      timeoutRate: 0.8,
      hintRate: 1.2,
      discriminationIndex: 0.29,
      distractors: [
        { optionIndex: 0, text: 'Amanah', count: 35, percentage: 2.1, isCorrect: false },
        { optionIndex: 1, text: 'Kompeten', count: 22, percentage: 1.3, isCorrect: false },
        { optionIndex: 2, text: 'Harmonis', count: 1537, percentage: 91.5, isCorrect: true },
        { optionIndex: 3, text: 'Loyal', count: 48, percentage: 2.9, isCorrect: false },
        { optionIndex: 4, text: 'Adaptif', count: 25, percentage: 1.5, isCorrect: false },
        { optionIndex: 5, text: 'Kolaboratif', count: 13, percentage: 0.7, isCorrect: false }
      ],
      signals: ['high_accuracy_floor']
    }
  },
  {
    id: 'q-tiu-numerik-05',
    sourceKey: 'TIU-NUM-2024-077',
    revision: 1,
    target: 'cpns',
    category: 'TIU',
    subcategory: 'Deret Angka',
    primarySkillId: 'deret_bertingkat',
    prerequisiteSkillIds: ['aritmatika_dasar'],
    prompt: '3, 6, 11, 18, 27, ..., ...',
    options: ['36, 47', '38, 51', '38, 49', '37, 50', '39, 52'],
    correctOptionIndex: 1,
    explanation: 'Pola selisih: +3, +5, +7, +9, maka berikutnya +11 (27+11 = 38) dan +13 (38+13 = 51).',
    difficulty: 3,
    standardTimeLimitMs: 50000,
    expectedTimeMs: 30000,
    curriculumWeight: 1.0,
    assessmentEligible: true,
    qualityState: 'disabled',
    smeApproved: false,
    approvedAt: null,
    approverReference: null,
    active: false,
    lastUsedAt: '2026-08-25T11:15:00Z',
    deactivatedAt: '2026-08-26T08:30:00Z',
    deactivationReason: 'Ditemukan ambiguitas penulisan opsi jawaban dan distractor tidak valid.',
    deactivatedBy: 'admin@yudha.app',
    metrics: {
      totalAttempts: 520,
      unseenAttempts: 410,
      overallAccuracy: 12.5,
      unseenAccuracy: 9.8,
      seenUnseenGap: 2.7,
      medianResponseTimeMs: 48000,
      timeoutRate: 22.1,
      hintRate: 35.0,
      discriminationIndex: -0.08,
      distractors: [
        { optionIndex: 0, text: '36, 47', count: 80, percentage: 15.4, isCorrect: false },
        { optionIndex: 1, text: '38, 51', count: 65, percentage: 12.5, isCorrect: true },
        { optionIndex: 2, text: '38, 49', count: 280, percentage: 53.8, isCorrect: false },
        { optionIndex: 3, text: '37, 50', count: 75, percentage: 14.4, isCorrect: false },
        { optionIndex: 4, text: '39, 52', count: 20, percentage: 3.9, isCorrect: false }
      ],
      signals: ['negative_discrimination', 'extremely_low_accuracy', 'high_timeout_rate']
    }
  },
  {
    id: 'q-twk-uud-06',
    sourceKey: 'TWK-UUD-2024-055',
    revision: 2,
    target: 'cpns',
    category: 'TWK',
    subcategory: 'UUD 1945',
    primarySkillId: 'uud_lembaga_negara',
    prerequisiteSkillIds: ['struktur_ketatanegaraan'],
    prompt: 'Menurut Pasal 24C Ayat (1) UUD 1945, Mahkamah Konstitusi berwenang mengadili pada tingkat pertama dan terakhir yang putusannya bersifat final untuk hal berikut, KECUALI...',
    options: [
      'Menguji undang-undang terhadap UUD',
      'Memutus sengketa kewenangan lembaga negara yang kewenangannya diberikan oleh UUD',
      'Memutus pembubaran partai politik',
      'Menguji peraturan perundang-undangan di bawah undang-undang terhadap undang-undang',
      'Memutus perselisihan tentang hasil pemilihan umum'
    ],
    correctOptionIndex: 3,
    explanation: 'Menguji peraturan perundang-undangan di bawah UU terhadap UU adalah kewenangan Mahkamah Agung (Pasal 24A Ayat 1), bukan MK.',
    difficulty: 4,
    standardTimeLimitMs: 60000,
    expectedTimeMs: 35000,
    curriculumWeight: 1.1,
    assessmentEligible: true,
    qualityState: 'approved',
    smeApproved: true,
    approvedAt: '2025-08-15T11:00:00Z',
    approverReference: 'SME-DOC-TWK-18',
    active: true,
    lastUsedAt: '2026-08-31T19:30:00Z',
    metrics: {
      totalAttempts: 1890,
      unseenAttempts: 1200,
      overallAccuracy: 52.4,
      unseenAccuracy: 46.8,
      seenUnseenGap: 5.6,
      medianResponseTimeMs: 38200,
      timeoutRate: 6.4,
      hintRate: 11.2,
      discriminationIndex: 0.51,
      distractors: [
        { optionIndex: 0, text: 'Menguji undang-undang terhadap UUD', count: 180, percentage: 9.5, isCorrect: false },
        { optionIndex: 1, text: 'Memutus sengketa kewenangan...', count: 210, percentage: 11.1, isCorrect: false },
        { optionIndex: 2, text: 'Memutus pembubaran partai politik', count: 320, percentage: 16.9, isCorrect: false },
        { optionIndex: 3, text: 'Menguji peraturan perundang-undangan...', count: 990, percentage: 52.4, isCorrect: true },
        { optionIndex: 4, text: 'Memutus perselisihan tentang hasil pemilu', count: 190, percentage: 10.1, isCorrect: false }
      ],
      signals: []
    }
  }
];

export const MOCK_REVIEW_CASES: ReviewCase[] = [
  {
    id: 'CASE-2026-089',
    questionId: 'q-tiu-silogisme-02',
    questionRevision: 1,
    target: 'cpns',
    category: 'TIU',
    skillId: 'silogisme_kategoris',
    promptSnippet: 'Semua ilmuwan berpikir kritis. Sebagian ilmuwan gemar menulis...',
    status: 'in_review',
    priority: 'high',
    signals: ['low_accuracy', 'suspicious_distractor_0', 'high_timeout_rate'],
    manualReason: 'Akurasi 24.5% jauh di bawah benchmark kesulitan 4. 49% responden memilih Opsi A karena kalimat ambigu.',
    evidenceSnapshot: {
      overallAccuracy: 24.5,
      unseenAccuracy: 18.2,
      timeoutRate: 18.6,
      hintRate: 26.4,
      medianResponseTimeMs: 54200,
      totalAttempts: 980,
      flaggedDistractors: [0]
    },
    assignedTo: 'admin@yudha.app',
    notes: [
      {
        id: 'note-1',
        author: 'admin@yudha.app',
        authorRole: 'Admin QA',
        timestamp: '2026-08-30T10:15:00Z',
        content: 'Distractor opsi A ("Semua yang gemar...") menjadi jebakan yang tidak fair karena bentuk kalimat mirip premis. Perlu direvisi redaksinya.'
      },
      {
        id: 'note-2',
        author: 'sme-logika@yudha.app',
        authorRole: 'SME Reviewer',
        timestamp: '2026-08-31T09:30:00Z',
        content: 'Setuju, kita jadwalkan revisi content revision 2 dan ubah opsi A agar lebih terbedakan.'
      }
    ],
    disposition: null,
    createdAt: '2026-08-29T14:00:00Z',
    updatedAt: '2026-08-31T09:30:00Z',
    resolvedAt: null,
    resolvedBy: null
  },
  {
    id: 'CASE-2026-074',
    questionId: 'q-tiu-numerik-05',
    questionRevision: 1,
    target: 'cpns',
    category: 'TIU',
    skillId: 'deret_bertingkat',
    promptSnippet: '3, 6, 11, 18, 27, ..., ...',
    status: 'resolved',
    priority: 'critical',
    signals: ['negative_discrimination', 'extremely_low_accuracy', 'high_timeout_rate'],
    manualReason: 'Kunci jawaban tertukar dengan opsi 3 pada seed awal.',
    evidenceSnapshot: {
      overallAccuracy: 12.5,
      unseenAccuracy: 9.8,
      timeoutRate: 22.1,
      hintRate: 35.0,
      medianResponseTimeMs: 48000,
      totalAttempts: 520,
      flaggedDistractors: [2]
    },
    assignedTo: 'admin@yudha.app',
    notes: [
      {
        id: 'note-3',
        author: 'admin@yudha.app',
        authorRole: 'Admin QA',
        timestamp: '2026-08-26T08:25:00Z',
        content: 'Soal telah dinonaktifkan (disabled) secara manual dan revision di-invalidate.'
      }
    ],
    disposition: 'deactivate_question',
    createdAt: '2026-08-25T16:00:00Z',
    updatedAt: '2026-08-26T08:30:00Z',
    resolvedAt: '2026-08-26T08:30:00Z',
    resolvedBy: 'admin@yudha.app'
  },
  {
    id: 'CASE-2026-092',
    questionId: 'q-bumn-akhlak-04',
    questionRevision: 1,
    target: 'bumn',
    category: 'Core Values',
    skillId: 'akhlak_harmonis',
    promptSnippet: 'Seorang karyawan selalu menghargai setiap orang apapun latar belakangnya...',
    status: 'open',
    priority: 'low',
    signals: ['high_accuracy_floor'],
    manualReason: 'Akurasi 91.5% terlalu mudah untuk tier tes lanjutan.',
    evidenceSnapshot: {
      overallAccuracy: 91.5,
      unseenAccuracy: 89.0,
      timeoutRate: 0.8,
      hintRate: 1.2,
      medianResponseTimeMs: 19400,
      totalAttempts: 1680
    },
    assignedTo: 'content-lead@yudha.app',
    notes: [],
    disposition: null,
    createdAt: '2026-08-31T08:00:00Z',
    updatedAt: '2026-08-31T08:00:00Z',
    resolvedAt: null,
    resolvedBy: null
  }
];

export const MOCK_COVERAGE: SkillCoverage[] = [
  {
    skillId: 'analogi_kata',
    skillName: 'Analogi Kata',
    category: 'TIU',
    target: 'cpns',
    activeCount: 45,
    underReviewCount: 2,
    disabledCount: 1,
    minimumRequired: 30,
    isBelowMinimum: false,
    difficultyDistribution: { 1: 8, 2: 12, 3: 15, 4: 7, 5: 3 }
  },
  {
    skillId: 'silogisme_kategoris',
    skillName: 'Silogisme Kategoris',
    category: 'TIU',
    target: 'cpns',
    activeCount: 18,
    underReviewCount: 4,
    disabledCount: 3,
    minimumRequired: 25,
    isBelowMinimum: true,
    difficultyDistribution: { 1: 2, 2: 4, 3: 6, 4: 4, 5: 2 }
  },
  {
    skillId: 'pancasila_sila_2',
    skillName: 'Pengamalan Sila ke-2',
    category: 'TWK',
    target: 'cpns',
    activeCount: 38,
    underReviewCount: 0,
    disabledCount: 0,
    minimumRequired: 20,
    isBelowMinimum: false,
    difficultyDistribution: { 1: 10, 2: 15, 3: 8, 4: 3, 5: 2 }
  },
  {
    skillId: 'uud_lembaga_negara',
    skillName: 'Lembaga Negara (UUD 1945)',
    category: 'TWK',
    target: 'cpns',
    activeCount: 22,
    underReviewCount: 1,
    disabledCount: 0,
    minimumRequired: 25,
    isBelowMinimum: true,
    difficultyDistribution: { 1: 3, 2: 6, 3: 7, 4: 4, 5: 2 }
  },
  {
    skillId: 'akhlak_harmonis',
    skillName: 'Harmonis (AKHLAK)',
    category: 'Core Values',
    target: 'bumn',
    activeCount: 32,
    underReviewCount: 1,
    disabledCount: 0,
    minimumRequired: 20,
    isBelowMinimum: false,
    difficultyDistribution: { 1: 12, 2: 10, 3: 6, 4: 3, 5: 1 }
  },
  {
    skillId: 'deret_bertingkat',
    skillName: 'Deret Angka Bertingkat',
    category: 'TIU',
    target: 'cpns',
    activeCount: 14,
    underReviewCount: 3,
    disabledCount: 5,
    minimumRequired: 30,
    isBelowMinimum: true,
    difficultyDistribution: { 1: 1, 2: 3, 3: 5, 4: 3, 5: 2 }
  }
];

export const MOCK_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'audit-001',
    timestamp: '2026-08-26T08:30:00Z',
    adminEmail: 'admin@yudha.app',
    action: 'deactivate_question',
    targetResource: 'question',
    resourceId: 'q-tiu-numerik-05',
    reason: 'Ditemukan ambiguitas penulisan opsi jawaban dan distractor tidak valid.',
    metadata: { revision: 1, invalidateRevision: true, caseId: 'CASE-2026-074' },
    idempotencyKey: 'idemp-deact-q-tiu-numerik-05-1724661000'
  },
  {
    id: 'audit-002',
    timestamp: '2026-08-29T14:00:00Z',
    adminEmail: 'admin@yudha.app',
    action: 'create_case',
    targetResource: 'review_case',
    resourceId: 'CASE-2026-089',
    reason: 'Auto-flagged due to low accuracy (24.5%) and high distractor 0 trap rate.',
    metadata: { questionId: 'q-tiu-silogisme-02', priority: 'high' },
    idempotencyKey: 'idemp-case-create-2026-089'
  },
  {
    id: 'audit-003',
    timestamp: '2026-08-31T08:00:00Z',
    adminEmail: 'admin@yudha.app',
    action: 'create_case',
    targetResource: 'review_case',
    resourceId: 'CASE-2026-092',
    reason: 'High accuracy ceiling audit flagged for difficulty re-evaluation.',
    metadata: { questionId: 'q-bumn-akhlak-04', priority: 'low' },
    idempotencyKey: 'idemp-case-create-2026-092'
  }
];
